# Generated by Django 5.1.4 on 2025-05-18 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_interviewquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewquestion',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_questions', to='core.lecture'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='core.batch'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='lectures/pdfs/'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='lectures/videos/'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='core.lecture'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.batch'),
        ),
    ]
